# Generated by Django 4.2.9 on 2026-04-18 22:47

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(default='📦', max_length=10, verbose_name='Icono')),
                ('color', models.CharField(default='#94a3b8', max_length=7, verbose_name='Color')),
                ('category_type', models.CharField(choices=[('expense', 'Gasto'), ('income', 'Ingreso'), ('both', 'Ambos')], default='expense', max_length=10, verbose_name='Tipo')),
                ('is_system', models.BooleanField(default=False, verbose_name='Es del sistema')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='Palabras clave')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('danger', 'Peligro'), ('success', 'Éxito')], default='info', max_length=10, verbose_name='Tipo')),
                ('alert_category', models.CharField(choices=[('budget_exceeded', 'Presupuesto excedido'), ('low_savings', 'Ahorro bajo'), ('negative_balance', 'Balance negativo'), ('goal_progress', 'Progreso de meta'), ('negative_trend', 'Tendencia negativa'), ('positive_trend', 'Tendencia positiva'), ('anomaly', 'Anomalía detectada'), ('general', 'General')], default='general', max_length=20, verbose_name='Categoría')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('is_dismissed', models.BooleanField(default=False, verbose_name='Descartada')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(verbose_name='Año')),
                ('month', models.IntegerField(verbose_name='Mes')),
                ('total_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total ingresos')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total gastos')),
                ('net_savings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Ahorro neto')),
                ('savings_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Tasa de ahorro')),
                ('health_status', models.CharField(choices=[('healthy', 'Saludable'), ('stable', 'Estable'), ('risky', 'En riesgo'), ('critical', 'Crítico'), ('unknown', 'Desconocido')], default='unknown', max_length=10, verbose_name='Estado de salud')),
                ('category_breakdown', models.JSONField(blank=True, default=dict, verbose_name='Desglose por categoría')),
                ('recommendations_count', models.IntegerField(default=0, verbose_name='Número de recomendaciones')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Snapshot Mensual',
                'verbose_name_plural': 'Snapshots Mensuales',
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['user', 'year', 'month'], name='core_monthl_user_id_393f2c_idx')],
                'unique_together': {('user', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Fuente')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('recurrence', models.CharField(choices=[('once', 'Una vez'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual'), ('yearly', 'Anual')], default='once', max_length=10, verbose_name='Recurrencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='core.category', verbose_name='Categoría')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='core_income_user_id_3b2ac5_idx'), models.Index(fields=['date'], name='core_income_date_790cb6_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('goal_type', models.CharField(choices=[('savings', 'Ahorro general'), ('emergency_fund', 'Fondo de emergencia'), ('debt_payment', 'Pago de deuda'), ('investment', 'Inversión'), ('purchase', 'Compra específica'), ('other', 'Otro')], default='savings', max_length=20, verbose_name='Tipo de meta')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto objetivo')),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto actual')),
                ('monthly_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Contribución mensual sugerida')),
                ('target_date', models.DateField(verbose_name='Fecha objetivo')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('completed', 'Completada'), ('paused', 'Pausada'), ('cancelled', 'Cancelada')], default='active', max_length=10, verbose_name='Estado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Meta Financiera',
                'verbose_name_plural': 'Metas Financieras',
                'ordering': ['target_date'],
                'indexes': [models.Index(fields=['user', 'status'], name='core_financ_user_id_d45282_idx'), models.Index(fields=['target_date'], name='core_financ_target__809993_idx')],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Es recurrente')),
                ('is_essential', models.BooleanField(default=True, verbose_name='Es esencial')),
                ('auto_classified', models.BooleanField(default=False, verbose_name='Auto-clasificado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Etiquetas')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.category', verbose_name='Categoría')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='core_expens_user_id_84343e_idx'), models.Index(fields=['date'], name='core_expens_date_d957f6_idx'), models.Index(fields=['category'], name='core_expens_categor_974cef_idx'), models.Index(fields=['is_essential'], name='core_expens_is_esse_ece9b1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='core_catego_slug_a504e5_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_system'], name='core_catego_is_syst_fbf4ad_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user'], name='core_catego_user_id_f22f43_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['user', 'is_read'], name='core_alert_user_id_56d82f_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['user', 'is_dismissed'], name='core_alert_user_id_e1e6af_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type'], name='core_alert_alert_t_0c2086_idx'),
        ),
    ]
